version: "3.8"
services:
    backend:
        build: ./backend/.dockerfile
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=db
            - DB_USER=postgres
            - DB_PASSWORD=dbpgAdmin
            - DB_NAME=skinx
        depends_on:
            - db
    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=dbpgAdmin
            - POSTGRES_DB=skinx
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres_data:
